[package]
name = "chrysalis"
version = "0.1.0"
edition = "2021"
authors = ["SL9-1994 <320sl91994@gmail.com>"]

[dependencies]
clap = {version = "4.5.4", features = ["derive"]}

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
